# Generated by Django 5.1.3 on 2024-12-18 09:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('APP', 'Appetizer'), ('MAIN', 'Main Course'), ('DESS', 'Dessert'), ('BEV', 'Beverage')], default='MAIN', max_length=4)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('recipe', models.JSONField(help_text='Ingredient quantities for the menu item')),
                ('preparation_time_minutes', models.PositiveIntegerField(help_text='Estimated preparation time in minutes', validators=[django.core.validators.MaxValueValidator(120)])),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('PROD', 'Produce'), ('MEAT', 'Meat'), ('DAIRY', 'Dairy'), ('BAKE', 'Bakery'), ('OTHER', 'Other')], default='OTHER', max_length=5)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('special_instructions', models.TextField(blank=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PEND', 'Pending'), ('PREP', 'Preparing'), ('READY', 'Ready'), ('COMP', 'Completed'), ('CANC', 'Cancelled')], default='PEND', max_length=9)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Liter'), ('ML', 'Milliliter'), ('PC', 'Piece')], default='G', max_length=3)),
                ('minimum_stock_level', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('storage_type', models.CharField(choices=[('COLD', 'Refrigerated'), ('FROZ', 'Frozen'), ('DRY', 'Dry Storage'), ('ROOM', 'Room Temperature')], default='DRY', max_length=4)),
                ('expiry_date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='inventory.supplier')),
            ],
        ),
    ]
